#!/usr/bin/env escript

%% charcount -- count characters in standard input
charcount() ->
    Input = ststd:getf(),
    charcount(Input, 0).

charcount(eof, Acc) ->
    ststd:putf("~w~n", [Acc]);
charcount([], Acc) ->
    charcount(eof, Acc);
charcount([_|T], Acc) ->
    charcount(T, Acc + 1).

main([]) ->
    charcount();
main(Arg) ->
    File = ststd:io({input, file}, Arg),
    charcount(File, 0).
