#!/usr/bin/escript

%% overstrike -- replace overstrikes by multiple lines
%%
%% BUGS
%% I'm not really sure what is an overstrike as I'm not used
%% to typewriters.
%% Also, Erlang inputs don't handle backspace \b or [8].
%% What overstrike is doing here is to mimick the output
%% from the book example, which is basically a underline.
%%
%% Correction: erlang shell can't handle backspace,
%% in terminal a backspace will be returned as `\b`,
%% and parsed as a blankspace in Erlang, instead of
%% deleting the last character (Pascal behavior).
%%
%% A Ctrl-D amid a word will break the program,
%% a Ctrl-D in a new (empty) line will finish the
%% program correctly.
overstrike(Input) ->
    overstrike(Input, [], []).

overstrike([], [], Acc) ->
    file:write_file("tmp", erlang:list_to_binary(Acc)),
    ststd:putf("~p~n", [Acc]);
overstrike([32|T], OverList, Acc) ->
    overstrike(T, lists:concat([OverList, [32]]), lists:concat([Acc, [32]]));
overstrike([10|T], OverList, Acc) ->
    overstrike(T, [], lists:concat([Acc, [10], OverList, [10]]));
overstrike([H|T], OverList, Acc) ->
    overstrike(T, lists:concat([OverList, "_"]), lists:concat([Acc, [H]])).

main([]) ->
    Input = ststd:getf(),
    overstrike(Input);
main(Arg) ->
    {ok, Bin} = file:read_file(Arg),
    File = erlang:binary_to_list(Bin),
    overstrike(File).
