#!/usr/bin/env escript

%% wc -- count words, lines and characters
%%
%% BUGS
%% If Ctrl-D during a word, will not count word or curent line.
wc() ->
    Input = ststd:getf(),
    wc(Input, false, 0, 0, 0).

wc([], _, WC, LC, CC) ->
    [LC, WC, CC];
wc([H|T], inword, WC, LC, CC) ->
    case lists:member(H, [9, 10, 32]) of
        true when H =:= 10 -> wc(T, false, WC+1, LC+1, CC+1);
        true -> wc(T, false, WC+1, LC, CC+1);
        false -> wc(T, inword, WC, LC, CC+1)
    end;
wc([H|T], _, WC, LC, CC) ->
    case lists:member(H, [9, 10, 32]) of
        true when H =:= 10 -> wc(T, false, WC, LC+1, CC+1);
        true -> wc(T, false, WC, LC, CC+1);
        false -> wc(T, inword, WC, LC, CC+1)
    end.

main([]) ->
    wc();
main(Arg) ->
    {ok, Bin} = file:read_file(Arg),
    File = erlang:binary_to_list(Bin),
    Ret = wc(File, false, 0, 0, 0),
    ststd:putf(" ~w ~w ~w ~s~n", Ret++Arg).
